services:
  image2body_backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "80:5000"
    # volumes:
    #   - .:/app
    env_file:
      - .env
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ "gpu" ]
              count: 1
              driver: nvidia
